In [17]:
import numpy as np
from itertools import islice



## Initialize Domains

In [57]:

A=[1,2,3,4]
B=[1,2,3,4]
C=[1,2,3,4]
D=[1,2,3,4]
E=[1,2,3,4]
F=[1,2,3,4]
G=[1,2,3,4]
H=[1,2,3,4]

    
def consistent(V,Constraints):
    V=V
    for constraint in Constraints:
        if not eval(constraint):
            return False
        
            
        
            

def take(n, iterable):
    "Return first n items of the iterable as a list"
    return list(islice(iterable, n))

    

## Define Constraints as dict

In [56]:
Constraints={'a':[],
             'b':[],
             'c':[],
             'd':['d!=c'],
             'e':['e!=c','e<(d-1)'],
             'f':['abs(f-b)==1','c!=f','d!=f','abs(e-f)%2!=0'],
             'g':['a>=g','abs(g-c)==1','d>=g','g!=f'],
             'h':['a<h','g<h','abs(h-c)%2==0','h!=d','e!=(h-2)','h!=f']}

In [58]:
Constraints['e']
V={'c': 4, 'd': 3,'e':2}
if not eval(Constraints['e'][1]):
    print("True")
else: 
    print("False")

False


In [59]:
d=3
c=4
e=2
V={'c': 3, 'd': 3,'e':2}
if consistent(V,Constraints['e']):
    print("satisfied")
else:
    print("Insatiable")

Insatiable


I couldn't print it the way it shows in the assignment. See if it works for you.

In [60]:
assignment={}
models=np.array([])
space='\t'
for a in A:
    assignment['a']=a
    n_items = take(1, assignment.items())
    print(n_items) 
    time=1
    for b in B:
        assignment['b']=b
        n_items = take(2, assignment.items())
        print(n_items)   
        time+=1
        for c in C:
            assignment['c']=c
            n_items = take(3, assignment.items())
            print(n_items)   
            time+=1
            for d in D:
                assignment['d']=d
                n_items = take(4, assignment.items())
                print(n_items)
                time+=1
                for constraint in Constraints['d']:
                    if not eval(constraint):
                        print('-> failure')
                        time-=1
                        flag=1
                        break
                if flag:
                    flag=0
                    continue
                
                for e in E:
                    assignment['e']=e
                    n_items = take(5, assignment.items())
                    print(n_items)
                    time+=1
                    for constraint in Constraints['e']:
                        if not eval(constraint):
                            print('-> failure')
                            time-=1
                            flag=1
                            break
                    if flag:
                        flag=0
                        continue
                        
                            
                    for f in F:
                        assignment['f']=f
                        n_items = take(6, assignment.items())
                        print(n_items)
                        time+=1
                        for constraint in Constraints['f']:
                            if not eval(constraint):
                                print('-> failure')
                                time-=1
                                flag=1
                                break
                        if flag:
                            flag=0
                            continue  
                            
                        for g in G:
                            assignment['g']=g
                            n_items = take(7, assignment.items())
                            print(n_items)
                            for constraint in Constraints['g']:
                                if not eval(constraint):
                                    print('-> failure')
                                    flag=1
                                    break  
                                        
                            if flag:
                                flag=0
                                continue
                                    
                                    
                            for h in H:
                                assignment['h']=h
                                n_items = take(8, assignment.items())
                                print(n_items)
                                for constraint in Constraints['h']:
                                    if not eval(constraint):
                                        print('-> failure')
                                        flag=1
                                        break
                                            
                                if flag:
                                    flag=0
                                    continue
                                                                            
                                print("Yay! we have a model")
                                model=np.array([a,b,c,d,e,f,g,h])
                                if not models.size:
                                    models=model
                                else:
                                    models=np.vstack((models,model))
                                                                        
                                                                
                                                            
                                                
                                            
                                            
                                            
                                            
                                            


[('a', 1)]
[('a', 1), ('b', 1)]
[('a', 1), ('b', 1), ('c', 1)]
[('a', 1), ('b', 1), ('c', 1), ('d', 1)]
-> failure
[('a', 1), ('b', 1), ('c', 1), ('d', 2)]
[('a', 1), ('b', 1), ('c', 1), ('d', 2), ('e', 1)]
-> failure
[('a', 1), ('b', 1), ('c', 1), ('d', 2), ('e', 2)]
-> failure
[('a', 1), ('b', 1), ('c', 1), ('d', 2), ('e', 3)]
-> failure
[('a', 1), ('b', 1), ('c', 1), ('d', 2), ('e', 4)]
-> failure
[('a', 1), ('b', 1), ('c', 1), ('d', 3)]
[('a', 1), ('b', 1), ('c', 1), ('d', 3), ('e', 1)]
-> failure
[('a', 1), ('b', 1), ('c', 1), ('d', 3), ('e', 2)]
-> failure
[('a', 1), ('b', 1), ('c', 1), ('d', 3), ('e', 3)]
-> failure
[('a', 1), ('b', 1), ('c', 1), ('d', 3), ('e', 4)]
-> failure
[('a', 1), ('b', 1), ('c', 1), ('d', 4)]
[('a', 1), ('b', 1), ('c', 1), ('d', 4), ('e', 1)]
-> failure
[('a', 1), ('b', 1), ('c', 1), ('d', 4), ('e', 2)]
[('a', 1), ('b', 1), ('c', 1), ('d', 4), ('e', 2), ('f', 1)]
-> failure
[('a', 1), ('b', 1), ('c', 1), ('d', 4), ('e', 2), ('f', 2)]
-> failure
[('a', 1)

[('a', 2), ('b', 4), ('c', 2), ('d', 4), ('e', 1)]
[('a', 2), ('b', 4), ('c', 2), ('d', 4), ('e', 1), ('f', 1)]
-> failure
[('a', 2), ('b', 4), ('c', 2), ('d', 4), ('e', 1), ('f', 2)]
-> failure
[('a', 2), ('b', 4), ('c', 2), ('d', 4), ('e', 1), ('f', 3)]
-> failure
[('a', 2), ('b', 4), ('c', 2), ('d', 4), ('e', 1), ('f', 4)]
-> failure
[('a', 2), ('b', 4), ('c', 2), ('d', 4), ('e', 2)]
-> failure
[('a', 2), ('b', 4), ('c', 2), ('d', 4), ('e', 3)]
-> failure
[('a', 2), ('b', 4), ('c', 2), ('d', 4), ('e', 4)]
-> failure
[('a', 2), ('b', 4), ('c', 3)]
[('a', 2), ('b', 4), ('c', 3), ('d', 1)]
[('a', 2), ('b', 4), ('c', 3), ('d', 1), ('e', 1)]
-> failure
[('a', 2), ('b', 4), ('c', 3), ('d', 1), ('e', 2)]
-> failure
[('a', 2), ('b', 4), ('c', 3), ('d', 1), ('e', 3)]
-> failure
[('a', 2), ('b', 4), ('c', 3), ('d', 1), ('e', 4)]
-> failure
[('a', 2), ('b', 4), ('c', 3), ('d', 2)]
[('a', 2), ('b', 4), ('c', 3), ('d', 2), ('e', 1)]
-> failure
[('a', 2), ('b', 4), ('c', 3), ('d', 2), ('e', 2)]
-

-> failure
[('a', 4), ('b', 3), ('c', 1), ('d', 2), ('e', 3)]
-> failure
[('a', 4), ('b', 3), ('c', 1), ('d', 2), ('e', 4)]
-> failure
[('a', 4), ('b', 3), ('c', 1), ('d', 3)]
[('a', 4), ('b', 3), ('c', 1), ('d', 3), ('e', 1)]
-> failure
[('a', 4), ('b', 3), ('c', 1), ('d', 3), ('e', 2)]
-> failure
[('a', 4), ('b', 3), ('c', 1), ('d', 3), ('e', 3)]
-> failure
[('a', 4), ('b', 3), ('c', 1), ('d', 3), ('e', 4)]
-> failure
[('a', 4), ('b', 3), ('c', 1), ('d', 4)]
[('a', 4), ('b', 3), ('c', 1), ('d', 4), ('e', 1)]
-> failure
[('a', 4), ('b', 3), ('c', 1), ('d', 4), ('e', 2)]
[('a', 4), ('b', 3), ('c', 1), ('d', 4), ('e', 2), ('f', 1)]
-> failure
[('a', 4), ('b', 3), ('c', 1), ('d', 4), ('e', 2), ('f', 2)]
-> failure
[('a', 4), ('b', 3), ('c', 1), ('d', 4), ('e', 2), ('f', 3)]
-> failure
[('a', 4), ('b', 3), ('c', 1), ('d', 4), ('e', 2), ('f', 4)]
-> failure
[('a', 4), ('b', 3), ('c', 1), ('d', 4), ('e', 3)]
-> failure
[('a', 4), ('b', 3), ('c', 1), ('d', 4), ('e', 4)]
-> failure
[('a', 4),

## Show models found 

In [61]:
print(models)


[[1 3 2 3 1 4 1 2]
 [2 2 3 4 2 1 2 3]
 [3 1 4 3 1 2 3 4]
 [3 3 4 3 1 2 3 4]]


In [24]:
assignment


{'a': 4, 'b': 4}